requires 'DBIx::Simple', '1.35';
requires 'Moose', '2.1000';
requires 'local::lib', '2.0';
requires 'Plack';
requires 'Task::Plack';
requires 'Plack::Request';
requires 'Starman';
requires 'Mojolicious';
requires 'Mojo::JSON';
requires 'JSON';
requires 'JSON::Parse', '0.32';
requires 'Crypt::PBKDF2', '0.101170';
requires 'Getopt::Whatever';
requires 'Switch';
requires 'DBIx::Class', '0.082820';
